-   id: valid-utf8
    name: Check for valid UTF-8
    description: Checks if file is valid utf-8 via iconv
    entry: bash -c 'iconv -f utf-8 -t utf-16 $@ > /dev/null'
    language: system
    types: [text]
-   id: cargo-fmt
    name: Run cargo fmt
    description: Formats rust code with nightly rustfmt
    entry: cargo +nightly fmt
    language: system
    files: \.rs$
    pass_filenames: false
-   id: commitlint
    name: Lint commit message
    description: Checks commit message
    language: system
    entry: commitlint --edit
    verbose: true
